
services:
  web:
    build: .
    container_name: flask_app
    command: python src/main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: owais
      POSTGRES_PASSWORD: owais123
      POSTGRES_DB: flights
    ports:
      - "5432:5432"
